// <auto-generated />
namespace CoCoCo_Facturatie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Korting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Korting));
        
        string IMigrationMetadata.Id
        {
            get { return "201709221629218_Korting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
